
services:
  postgres:
    image: postgres:16
    container_name: agendador-postgres
    restart: always
    environment:
      POSTGRES_DB: agendador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: