spring.application.name=agendador-horarios

# Se não encontrar a variável de sistema, usa o valor padrão depois dos dois pontos (:)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/agendador}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1234}

# Configurações de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect